openapi: 3.1.0
info:
  title: MQ Probe API
  version: 1.0.0
servers: [{ url: / }]
paths:
  /health/live:
    get: { summary: Liveness, responses: { "200": { description: OK } } }
  /health/ready:
    get: { summary: Readiness, responses: { "200": { description: OK } } }
  /status:
    get:
      summary: Status
      responses: { "200": { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/Status' } } } } }
  /config:
    get: { summary: Get runtime config, responses: { "200": { description: OK } } }
    put:
      summary: Update runtime config
      requestBody: { required: true, content: { application/json: { schema: { $ref: '#/components/schemas/RuntimeConfigUpdate' } } } }
      responses: { "200": { description: Updated } }
  /connections/test:
    post:
      summary: Test MQ connection
      requestBody: { required: true, content: { application/json: { schema: { $ref: '#/components/schemas/ConnectionTestReq' } } } }
      responses: { "200": { description: OK } }
  /queues/{queueName}/depth:
    get:
      summary: Queue depth
      parameters: [{ name: queueName, in: path, required: true, schema: { type: string } }]
      responses: { "200": { description: OK } }
  /queues/{queueName}/stats:
    get:
      summary: Queue probe stats
      parameters: [{ name: queueName, in: path, required: true, schema: { type: string } }]
      responses: { "200": { description: OK } }
  /queues/{queueName}/messages:put:
    post:
      summary: Put messages batch
      parameters:
        - { name: queueName, in: path, required: true, schema: { type: string } }
      requestBody:
        required: true
        content: { application/json: { schema: { $ref: '#/components/schemas/PutBatchReq' } } }
      responses:
        "201": { description: Enqueued, headers: { Idempotent-Replay: { schema: { type: string } } } }
      headers:
        Idempotency-Key: { schema: { type: string, format: uuid } }
  /queues/{queueName}/messages:get:
    post:
      summary: Get messages batch
      parameters:
        - { name: queueName, in: path, required: true, schema: { type: string } }
      requestBody:
        required: true
        content: { application/json: { schema: { $ref: '#/components/schemas/GetBatchReq' } } }
      responses:
        "200": { description: Fetched }
  /queues/{queueName}/purge:
    post:
      summary: Purge queue (test only)
      responses: { "202": { description: Purging } }
  /tests:
    get: { summary: List tests, responses: { "200": { description: OK } } }
    post:
      summary: Create test job
      requestBody: { required: true, content: { application/json: { schema: { $ref: '#/components/schemas/TestJobReq' } } } }
      responses: { "202": { description: Started } }
  /tests/{testId}:
    get: { summary: Get test status, parameters: [{ name: testId, in: path, required: true, schema: { type: string } }], responses: { "200": { description: OK } } }
  /tests/{testId}/stop:
    post: { summary: Stop test, responses: { "202": { description: Stopping } } }
components:
  schemas:
    RuntimeConfigUpdate:
      type: object
      properties:
        defaultBatchSize: { type: integer, minimum: 1 }
        defaultMsgSizeBytes: { type: integer, minimum: 0 }
        defaultWaitSeconds: { type: integer, minimum: 0, maximum: 60 }
        defaultQueue: { type: string }
    ConnectionTestReq:
      type: object
      required: [queueManager]
      properties:
        queueManager: { type: string }
        channel: { type: string }
        connName: { type: string }
        ccdtUrl: { type: string, nullable: true }
        queue: { type: string }
        ccsid: { type: integer }
        ssl:
          type: object
          properties:
            enabled: { type: boolean }
            keyStoreRef: { type: string }
            trustStoreRef: { type: string }
        auth:
          type: object
          properties:
            user: { type: string }
            passwordRef: { type: string }
    PutBatchReq:
      type: object
      required: [count]
      properties:
        count: { type: integer, minimum: 1 }
        messageSizeBytes: { type: integer, minimum: 0 }
        payload:
          type: object
          properties:
            mode: { type: string, enum: [random, fixed, template] }
            fixedBase64: { type: string, nullable: true }
            template: { type: string, nullable: true }
        mqProps:
          type: object
          properties:
            persistence: { type: string, enum: [persistent, nonpersistent] }
            priority: { type: integer, minimum: 0, maximum: 9 }
            expiryMs: { type: integer, minimum: 0 }
            correlIdMode: { type: string, enum: [none, echoMsgId, fixed] }
            fixedCorrelIdBase64: { type: string, nullable: true }
        headers: { type: object, additionalProperties: { type: string } }
        grouping:
          type: object
          properties:
            enabled: { type: boolean }
            groupSize: { type: integer, minimum: 1 }
        rateLimitPerSec: { type: integer, minimum: 1, nullable: true }
        transaction:
          type: object
          properties:
            enabled: { type: boolean }
            txSize: { type: integer, minimum: 1 }
    GetBatchReq:
      type: object
      properties:
        maxMessages: { type: integer, minimum: 1, default: 1 }
        waitSeconds: { type: integer, minimum: 0, maximum: 60, default: 20 }
        browseOnly: { type: boolean, default: false }
        selector:
          type: object
          properties:
            correlIdBase64: { type: string, nullable: true }
            msgIdBase64: { type: string, nullable: true }
        conversion:
          type: object
          properties:
            ccsid: { type: integer }
            convert: { type: boolean }
        transaction:
          type: object
          properties:
            enabled: { type: boolean }
            txSize: { type: integer, minimum: 1 }
        ack: { type: string, enum: [commit, rollback, none], default: commit }
    TestJobReq:
      type: object
      required: [name, queue, durationSeconds]
      properties:
        name: { type: string }
        queue: { type: string }
        durationSeconds: { type: integer, minimum: 1 }
        producers: { type: integer, minimum: 0, default: 1 }
        consumers: { type: integer, minimum: 0, default: 0 }
        rateTargetMsgPerSec: { type: integer, minimum: 1 }
        producerConfig: { $ref: '#/components/schemas/PutBatchReq' }
        consumerConfig: { $ref: '#/components/schemas/GetBatchReq' }
  securitySchemes:
    bearerAuth: { type: http, scheme: bearer, bearerFormat: JWT }
